### PR TITLE
Added CPP11 features. Fixed Y-collision bug. Minor fixes.

### LINKED ISSUE #14: Add CPP11 features
Use range-based for loops.
Add initializer list to FigureList.
Add override to functions.
Make singleton non-copyable.
Print figure count in each quadrant (count_if + lambda)

### PR DESCRIPTION
**Pull request by cynex0**
Closes #14 
Collisions on Y-axis now work properly.
Changed player controls to arrows.

### CODE REVIEW

File: game/AllegroApp.cpp [hunk 1]
```diff
@@ -70,11 +70,22 @@ void AllegroApp::OnKeyDown(const ALLEGRO_KEYBOARD_EVENT& keyboard)
...
-            cout << figureList.getFig(i)->ToString() << endl;
+        for (Figure* fig : figureList.getList()) {
+            std::cout << fig->ToString() << std::endl;
         }
         break;
     }
+    case ALLEGRO_KEY_S:
+    {
+        std::vector<int> quadrants;
+        for (Figure* fig : figureList.getList()) {
```
Comment (shadowreplicant) [inline game/AllegroApp.cpp:81]: а зачем тут `for`?
`fig` не используется в теле цикла
